### ISSUE TITLE
Release not yet ready

### ISSUE THREAD

**Issue by KenZync** [dandykong/nopssdk#1]

**Comment by dandykong** [comment]
I'm still working on getting everything back up, I'll get a release out once I figure out how the author is modifying `PsPcSdk.dll`.

**Comment by tscftw** [comment]
Here's a reupload of the release on Nexusmods if you want to use that for the release
https://www.nexusmods.com/godofwarragnarok/mods/51

**Comment by dandykong** [comment]
Download link is now up. I still have no idea why it needs to redistribute the Playstation PC runtime without even touching it.
