### ISSUE TITLE
Latest game update may have hardened PSN enforcement, more testing needed.

### ISSUE THREAD

**Issue by ClaudeLib** [dandykong/nopssdk#4]
On October 1st, the developers released patch 4 which, among other things, "fixed multiple issues related to authentication flow and provided more communication as to what is happening to the user". Intentionally or not, it has also broken the bypass, and now the game is stuck on the "Waiting for response from authentication server" screen.
![2322010_20241002105544_1](https://github.com/user-attachments/assets/50a5aa0a-954c-411c-969d-28040b21638c)

**Comment by ClaudeLib** [comment]
Update: the game seems to run fine with "SteamDeck=0" environment variable override in launch options. So the issue can be closed now, I guess.

**Comment by dandykong** [comment]
"fixed multiple issues related to authentication flow" and failing to connect sounds like an anti-circumvention measure.

I forked this for archival purposes and don't actually have the game or even a PSN account, and I have no intention of getting one in order to keep this repo immune to their EULA. If they do eventually patch the `SteamDeck=0` bypass I'll need contributors who actually have the game to fix it.

I'll keep this issue open while the situation develops.

**Comment by ClaudeLib** [comment]
To be quite honest, after thinking about it really hard, I think my initial panic is just due to a fact that I last played the game on my main PC, where the env var override is already present, while today I was using my Deck without it, so initial behavior was different. I guess the only thing this really did was add the "Waiting" message instead of showing black screen during the time when I'm supposed to log into the PSN account. I'll try downgrading the game back to 3.1 to see if I'm correct.

**Comment by dandykong** [comment]
Steam Decks are Linux machines, that's why.

It may have just been user error.

**Comment by ClaudeLib** [comment]
I checked the version 3.1, literally the only thing that's changed is that with the `SteamDeck` env var set to 1, the older versions sat on a black screen while the user was supposed to log into PSN, while version 4 now shows the "Waiting" message. With `SteamDeck=0` both versions start fine. How can I delete the issue? I feel stupid for creating it without checking properly beforehand.

**Comment by dandykong** [comment]
I'll go ahead and close it then.
