### ISSUE TITLE
[Build/documentation] PsPcSdk.dll is not built because the mod uses the original unmodified version.

### ISSUE THREAD

**Issue by nl255** [dandykong/nopssdk#5]
I noticed your readme says it does not build PsPcSdk.dll for some reason.  I checked the file both locally and through virustotal and it turns out the PsPcSdk.dll is the original unmodified version with Sony's digital signature still intact, apparently all the magic happens through version.dll.

**Comment by dandykong** [comment]
Thanks, updating the readme.
